-- Migration: Create embedding_jobs table for automatic embedding generation
-- This follows the Supabase "Automatic Embeddings" pattern

-- Enable pgvector extension if not already enabled
create extension if not exists vector;

-- Table to queue embedding generation jobs
create table if not exists embedding_jobs (
    id bigint generated by default as identity primary key,
    post_id uuid not null,
    created_at timestamptz default now(),
    processed boolean default false,
    error text,
    retry_count int default 0
);

-- Index for fast lookup of unprocessed jobs
create index if not exists idx_embedding_jobs_unprocessed
on embedding_jobs (processed, created_at)
where processed = false;

-- Index for looking up by post_id
create index if not exists idx_embedding_jobs_post_id
on embedding_jobs (post_id);

-- Function to enqueue embedding job when a post is inserted
create or replace function enqueue_embedding_job()
returns trigger as $$
begin
    -- Only enqueue if this is a new post (not an update)
    if TG_OP = 'INSERT' then
        insert into embedding_jobs (post_id)
        values (new.id);
    end if;
    return new;
end; $$ language plpgsql;

-- Trigger to enqueue embedding job on post insert
drop trigger if exists trg_posts_enqueue_embedding on posts;
create trigger trg_posts_enqueue_embedding
    after insert on posts
    for each row
    execute procedure enqueue_embedding_job();

-- Function to update embedding for a post
create or replace function update_post_embedding(p_post_id uuid)
returns void as $$
declare
    v_post record;
    v_embedding vector;
    v_combined_text text;
begin
    -- Get the post content
    select * into v_post from posts where id = p_post_id;
    
    if not found then
        raise exception 'Post not found: %', p_post_id;
    end if;
    
    -- Generate combined text for embedding
    v_combined_text := coalesce(v_post.title, '') || ' ' || coalesce(v_post.short_excerpt, '');
    
    -- The embedding will be generated by the application code
    -- This function just marks the job as ready for processing
    raise notice 'Embedding job enqueued for post: %', p_post_id;
end; $$ language plpgsql;

-- Grant execute on functions to authenticated users
grant execute on function enqueue_embedding_job() to authenticated, service_role;
grant execute on function update_post_embedding(uuid) to authenticated, service_role;
